name: Migrate Work Items

on:
  workflow_dispatch:
    inputs: 
      ado-org:
        description: 'ado-org'
        required: true
        default: 'HCLGurukul'
      ado-project:
        description: 'ado-project'
        required: true
        default: 'Knowledgebase'
      ado_area_path:
        description: 'ADO area path to migrate - uses the UNDER operator'
        required: true
        default: 'Knowledgebase/Knowledgebase'
      ado_migrate_closed_workitems:
        description: 'Migrate closed work items'
        required: true
        type: boolean
        default: 'true'
      ado_production_run:
        description: tag migrated work items with migrated-to-github and add discussion comment
        required: true
        type: boolean
        default: 'true'
      gh-org:
        description: 'gh-org'
        required: true
        default: 'Rameshnakkela'
      gh-repo:
        description: 'gh-org'
        required: true
        default: 'Knowledgebase'
      gh_update_assigned_to:
        description: 'Update Assigned To'
        required: true
        type: boolean
        default: 'true'
      gh_assigned_to_user_suffix:
        description: 'EMU suffix'
        required: true
        default: '_corp'
      gh_add_ado_comments:
        description: 'Add ADO Comments'
        required: true
        type: boolean
        default: 'true'

jobs:
  migrate:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@main
      
      - uses: tibdex/github-app-token@v1
        id: get_installation_token
        with: 
          app_id: 363245
          installation_id: 39795972
          private_key: "-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEAr1SkAvWNyVvW7Qvw00K4/S7DMu22AfF+bPNHvyp3aZhecqnJ\n3uCMsuCTPhz45GS4NhrMGf9EcL0s4W+AyBjp4ZQ6ACr4jAjKD1oJzQkc9P/qTYjv\nRVnSN8d0jJ6/ctvcVse2kslQdqwr7WnOs6qnlt+AVd41bhvqmtYkByX+Jv4Hivbm\nM6u2fb1nqElcwralFbSky/EDrFynoDNzyEZGcuKivjAjFQIRx1j3f6vkgKT+kRZf\ngkx3yW/BVdirFVjwrr18Hp0DuUFr+bLAcxeViUocW5hYXUNSO0HdmFhb9UT6z9PP\nIWM8F1hW/nI5rfTwQ3SrFcvNHAT3hLb/SgEr6wIDAQABAoIBADgtr6u/EGJPigtE\nQzL98xY00JjV7/apcW/pd7i6G677AnBNFQDUBGEgci15zQopd5jmdzVxRHW3N9U4\nDBSRXwdHnloFasQ74LqQiAlpfRzHj0SutrQK9r+mqiKQjxl3dx9bOJXJ6X1M53pX\n58JL0Q0XqiBZZddVHJPmP38G3muRe9ZNquc5zqUMr3mPRKIQFSGoviOO/Kk+wMr2\n/gPaxXAqFmlxgM9VT5IUMq+v2q5+ra+Xx//EqfssfDKHnlSnxbyQUwu8IV08I59H\nTk4YdTPSRdkG5V/AYheW8pPQk+YRVVECQFdkbSJbsRqMAIAyY845gY9ga5xtMjkY\nDNpAzYkCgYEA31QxDQbc0BPDvXFr1gCyHPrDEJD+/naJjirJLuW1WruYGX1jUNl6\nS81JUvjGawaoVoDrvf1ulzwTxAqjnKWEUWz03ZP0asB1UZBbzldyxmlpWpqa3UAg\nJNlhhQl9uEyIvQl9xHiRcVKWiww+MmXOHCLX5EamfcF6B6oreMnzD8UCgYEAyPri\nXFcEZV+VnmLRNglvtotMSG9N8DCmimmIDVUODvLsY8iVyabrf1MrGYzgJ5v7wI06\nmBByO7HK74rGDvtquc4T3gUN/UaCVjpYD2kPVLXxrpw5nVBkPit0ejhuBT2cE50o\n9HCDCAsgPDLNZ07xhGDRo7/F5yV6Nw7gvdTr1+8CgYB09w9Jl1KG2BMoYQLtbifa\n7arEPmyOsV6Ryu7bVQuKnb2ne/hMG9rlYHsKraid3TrFM3hEZTtKkfh4MGpIXJfU\nXZBRjG/yiSHougabJ0nBiOvYvChnwHIVWpSsrK/fmpXzC8mG4O6rv2mBIcRheNhd\n/BG+SRJhwrc61HE4LezTUQKBgQCxCRZWIqyTo4QHFaKWR++oy8FxWOI9fo1lBRq8\nK70Le/6w0uLm02tEJ/2iLw7QtT0o2v7PLkWBwdYx9XsLfXoAm7+yZZ9yCCcNT618\nPZ4sj2yJ08GIimUSwnKCqqx3X1LZkCmgUG+LqUlG3bVDmC1031grNuVb/A5Q64Ea\nlrD87wKBgQCfufBqh773cvOAjDarOCgrc+oSrwaL2+XdQUfPl7shseHiSXWyRMEX\nUhVTVudBC8+/Rs2G9lMky/sqcS5VbLCz87XAAzyWishJ9NAAHuMjiUH5kSfDUtgP\n/TGqO4E/T9V2+TeVDG+BoVFdj2LiIStfRK5Y1NcH3q62MlXpMCLbRg==\n-----END RSA PRIVATE KEY-----"
      
      - name: run migration
        shell: pwsh
        run: |
          # run migration script
          
          # cleaning up bools
          $ado_migrate_closed_workitems=$false
          $ado_production_run=$false
          $gh_update_assigned_to=$false
          $gh_add_ado_comments=$false
          
          if("${{ github.event.inputs.ado_migrate_closed_workitems }}" -eq "true") {
            $ado_migrate_closed_workitems=$true
          }

          if("${{ github.event.inputs.ado_production_run }}" -eq "true") {
            $ado_production_run=$true
          }

          if("${{ github.event.inputs.gh_update_assigned_to }}" -eq "true") {
            $gh_update_assigned_to=$true
          }
          
          if("${{ github.event.inputs.gh_add_ado_comments }}" -eq "true") {
            $gh_add_ado_comments=$true
          }
          
          ./ado_workitems_to_github_issues.ps1 -ado_pat "qar43ecqvurygbvc6ecagaduzhaeaw2jjudjwtophqfq6acrwd4a" -ado_org "HCLGurukul" -ado_project "Knowledgebase" -ado_area_path "Knowledgebase" -ado_migrate_closed_workitems $ado_migrate_closed_workitems -ado_production_run $ado_production_run -gh_pat "mb2pf5ni3tijdu7c2ipnjvvzvgebvylfep2euhwkslqytmo47wta" -gh_org "Rameshnakkela" -gh_repo "Knowledgebase" -gh_update_assigned_to $gh_update_assigned_to -gh_assigned_to_user_suffix "${{ github.event.inputs.gh_assigned_to_user_suffix }}" -gh_add_ado_comments $gh_add_ado_comments
          
